#!/bin/sh

battery_dir="/sys/class/power_supply/BAT0"

capacity=$(cat $battery_dir/capacity)
power_now=$(cat $battery_dir/power_now)
energy_now=$(cat $battery_dir/energy_now)
status=$(cat $battery_dir/status)

if [ $status = 'Unknown' ]; then
	echo "" # usually means full
	exit 0
else
	remaning_minutes=$(echo ${power_now} ${energy_now} | awk '{ printf "%d", $2 / $1 * 60 }')
	until_empty=$(date -d "+${remaning_minutes} minutes" "+%H:%M")
fi

echo \
	${capacity} \
	${power_now} \
	${remaning_minutes} \
	${until_empty} \
	| awk '{ printf "%d% (%1.2fW) %1.2fh ( %s)\n", $1, $2 * 10^-6, $3 / 60, $4 }'
